---
title: "ESM 204: Practice Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note: The actual final will be somewhat shorter than this practice exam.

1. Community A is composed of residents that have historically been disadvantaged. Community B is composed of wealthy residents.
Polluters in A have pollution demand: P = 20 − Q_A, where Q_A is pollution in A.
Polluters in B have pollution demand: P = 20 − 2*Q_B.

(a) Without any regulation, how much pollution do you expect in each community?
Is there an Environmental Justice problem (i.e. is there more pollution in the
disadvantaged community)?

(b) Suppose a standard is set where pollution cannot exceed Q¯ = 6 in any community. What is the cost to firms in A of achieving this standard? What is the
cost to firms in B? What is the total cost?

(c) Suppose firms in A are allowed to pollute 6 and firms in B are allowed to
pollute 6, and that they are allowed to trade pollution rights. What would be
the trading price of pollution permits? Which firm would buy and which firm
would sell, and how much?

(d) What are the EJ implications of each of the following policies:

i. No regulation

ii. Standard of 6 everywhere, and

iii. Cap and trade (with cap of 6 in A and cap of 6 in B, and subsequent
trading)


2. The demand for river rafting trips down the Colorado River is given by: P = 500 − Q/2 (where P is \$/trip and Q is number of trips each summer). The cost of providing each trip (paying the guide, raft, food, etc.) is \$100.

(a) If there is a free market for rafting trips, how many trips would you expect? What would be the price of a trip?


(b) Suppose that each trip also imposes some external costs, through congestion, litter, wildlife disturbance, etc. The Qth trip imposes an external cost of 3Q/2. Draw the demand, marginal private cost, and marginal external cost curves.

(c) Taking all private and external costs into account, what is the socially optimal number of rafting trips on the Colorado River?

(d) List 3 interventions that could achieve the socially optimal number of trips (with a 1-2 sentence explanation of how each intervention works).


3. Felicity’s utility function is given by U(X) = X ^ 1.3, where X is a monetary payoff.

(a) Is Felicity Risk Averse or Risk Loving?

(b) Felicity is throwing darts at the county fair and has already popped the requisite
3 balloons to win a prize. She faces the following options:

• Option A: Stop playing now, and receive a payoff of $10, or

• Option B: Throw one more dart with the following payoff:
- $100 If she pops a balloon and
– $0 if she does not pop a balloon.

If Felicity believes the probability she will pop a balloon is p = 0.1, will she
choose Option A or Option B?

(c) In a sudden boost of confidence, Felicity now thinks p = 0.2. Which option does
she choose?

4. Dam removal is extremely costly, but can deliver long-term ecological benefits. The cost of removing the Big River dam is \$100 million, which has to be paid immediately. Starting one year from now, there are other remediation costs of \$5 million per year for 5 years. The benefit of dam removal is \$10 million per year, starting in year 20. This benefit occurs every year and goes on forever.
(Hint: Remember that for any reasonable positive value of r, you only need to go out 100 years or so before the present value becomes very small. so if you do this numerically, you only need to run it out for about 100 years to decide which policy is better. )

(a) If the discount rate is r = 0, what is the present value of costs? What is the present value of benefits? Do the benefits of dam removal outweigh the costs?

(b) If the discount rate is r = .05, do the benefits outweigh the costs? If the discount rate is r = .01, do the benefits outweigh the cost?

5. A researcher named Sara is interested in the value of urban trees as an ecosystem service. She has gathered a dataset on home values in cities across the US. For each home, Sara knows:

(1) the home value (Vi , in dollars)
(2) the tree cover in the city (Ti, which is a score between 0 and 10), and other characteristics she uses as controls, so you can assume Ti is the only variable that affects home value Vi. Sara runs the following regression:

Vi = β0 + β1 * Ti + Controls + εi

where i indicates the home. From this regression, Sara obtains the following estimates:

βˆ0 = 300,000

βˆ1 = 400.

(a) Does more tree cover increase a home’s value? By how much?

(b) Los Angeles currently has tree cover of T = 3 and they are considering a campaign to increase tree cover to T = 5. By how much would this additional tree cover raise the value of each house in Los Angeles?

(c) Suppose there are 1,000,000 houses in Los Angeles. If the cost of the tree campaign in Los Angeles is $10,000,000 do the benefits outweigh the costs?





